# Write your MySQL query statement below
# SELECT A.NAME AS EMPLOYEE
#   FROM EMPLOYEE A
#        JOIN EMPLOYEE B ON A.MANAGERID = B.ID 
#  WHERE A.SALARY > B.SALARY 
 
SELECT A.NAME AS EMPLOYEE
  FROM EMPLOYEE AS A, EMPLOYEE AS B
 WHERE A.MANAGERID = B.ID
       AND A.SALARY > B.SALARY