# Write your MySQL query statement below
# SELECT C.NAME AS 'Customers'
#   FROM CUSTOMERS C
#   LEFT JOIN ORDERS O ON C.ID = O.CUSTOMERID
#  WHERE O.CUSTOMERID IS NULL

SELECT CUSTOMERS.NAME AS 'Customers'
  FROM CUSTOMERS
 WHERE CUSTOMERS.ID NOT IN
       (SELECT CUSTOMERID 
          FROM ORDERS)