# Write your MySQL query statement below
SELECT P.PRODUCT_ID, ROUND(SUM(P.PRICE * S.UNITS) / SUM(S.UNITS), 2) AS AVERAGE_PRICE
  FROM PRICES AS P
       JOIN UNITSSOLD AS S ON P.PRODUCT_ID = S.PRODUCT_ID
                              AND S.PURCHASE_DATE BETWEEN P.START_DATE AND P.END_DATE
 GROUP BY P.PRODUCT_ID