# Write your MySQL query statement below
SELECT C.CUSTOMER_ID, C.NAME
  FROM CUSTOMERS AS C
       JOIN ORDERS AS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
       JOIN PRODUCT AS P ON O.PRODUCT_ID = P.PRODUCT_ID
 GROUP BY C.CUSTOMER_ID
HAVING SUM(IF(MONTH(O.ORDER_DATE) = 6, quantity, 0) * price) >= 100
       AND SUM(IF(MONTH(O.ORDER_DATE) = 7, quantity, 0) * price) >= 100
