# Write your MySQL query statement below
# SELECT COUNT(*)
SELECT COUNT(*) AS ACCOUNTS_COUNT
  FROM STREAMS AS ST
       JOIN SUBSCRIPTIONS AS SU ON ST.ACCOUNT_ID = SU.ACCOUNT_ID
 WHERE YEAR(SU.START_DATE) <= 2021 AND YEAR(SU.END_DATE) >= 2021
       AND ST.ACCOUNT_ID NOT IN (SELECT ACCOUNT_ID
                                   FROM STREAMS
                                  WHERE YEAR(STREAM_DATE) = 2021)
